const $=id=>document.getElementById(id);let uploaded='';const brand={elkass:{n:'ELKASS',logo:'../assets/social/elkass-logo.svg',phone:'34 358 24 42',addr:'Olesno, Armii Krajowej 5',web:'elkass-store.vercel.app',cls:'brand-elkass'},agd:{n:'AGD Olesno',logo:'../assets/social/agd-olesno-logo.svg',phone:'123 456 789',addr:'Olesno, ul. Kościelna 1',web:'agdolesno.pl',cls:'brand-agd'}};const titles={standard:'OKAZJA RTV/AGD',hit:'HIT TYGODNIA',promo:'PROMOCJA DNIA',new:'NOWOŚĆ',black:'BLACK WEEK',cyber:'CYBER WEEK',christmas:'ŚWIĄTECZNA OFERTA',mikolajki:'MIKOŁAJKOWA OKAZJA',newyear:'NOWY ROK',winter:'ZIMOWA OFERTA',spring:'WIOSENNA OFERTA',easter:'WIELKANOCNA OKAZJA',summer:'LETNIA OFERTA',autumn:'JESIENNA OFERTA',school:'POWRÓT DO SZKOŁY',valentine:'WALENTYNKI',home:'AGD DO NOWEGO DOMU',raty:'RATY 0%',delivery:'DOSTAWA I MONTAŻ'};const tcls={black:'black',cyber:'cyber',christmas:'christmas',mikolajki:'christmas',easter:'easter',summer:'summer',school:'school'};function lines(v){return String(v||'').split('
').map(x=>x.trim()).filter(Boolean).slice(0,6)}function d(){let b=brand[$('brand').value];let th=$('theme').value;return {b,th,title:titles[th]||'OFERTA',f:$('format').value,name:$('name').value,price:$('price').value,cat:$('category').value,img:uploaded||$('imgText').value,features:lines($('features').value),cta:$('cta').value}}function icon(c){return {fridge:'❄',tv:'▣',washer:'↻',freezer:'❄',oven:'◼',soundbar:'♪',laptop:'⌘',smallagd:'✓'}[c]||'✓'}function bg(c){return {fridge:'tło: kuchnia premium',tv:'tło: salon RTV',washer:'tło: pralnia',freezer:'tło: spiżarnia',oven:'tło: zabudowa AGD',soundbar:'tło: salon audio',laptop:'tło: technologia',smallagd:'tło: dom'}[c]||'tło: auto'}function cls(x){return ['canvas',x.f==='story'?'story':x.f==='reels'?'reels':x.f==='news'?'news':'post',x.b.cls,tcls[x.th]||''].join(' ')}function post(x){let a=x.title.split(' ');let fs=x.features.length?x.features:['Oferta specjalna'];return `<div class="bg"></div><div class="note">${bg(x.cat)}</div><img class="logo" src="${x.b.logo}"><div class="badge">${a[0]}<small>${a.slice(1).join(' ')||'TYGODNIA'}</small></div><img class="prod" src="${x.img}" onerror="this.src='https://placehold.co/600x800?text=Produkt'"><div class="pname">${x.name}</div><div class="features">${fs.map(v=>`<div class="feature"><i>${icon(x.cat)}</i><span>${v}</span></div>`).join('')}</div><div class="price">${x.price.replace(' zł','')} <span>zł</span></div><div class="cta">${x.cta} ›</div><div class="foot"><span>📍 ${x.b.addr}</span><span>☎ ${x.b.phone}</span><span>🌐 ${x.b.web}</span></div>`}function reels(x){let fs=x.features.length?x.features:['Oferta'];let scenes=[{t:'0–2 s',h:`<img src="${x.b.logo}"><b>${x.title}</b>`},{t:'2–4 s',h:`<img src="${x.img}"><b>${x.name}</b>`},...fs.map((v,i)=>({t:`${4+i}–${5+i} s`,h:`<div style="font-size:54px">${icon(x.cat)}</div><b>${v}</b>`})),{t:'10–15 s',h:`<b>TYLKO TERAZ</b><div style="font-size:54px">${x.price}</div><img src="${x.b.logo}"><small>${x.b.phone}</small>`}].slice(0,8);return `<div class="reelwrap"><h2>Storyboard rolki — ${x.title}</h2><div class="reelscenes">${scenes.map(s=>`<div class="scene">${s.h}<div class="time">${s.t}</div></div>`).join('')}</div></div>`}function news(x){let fs=x.features.length?x.features:['Oferta'];return `<div class="newswrap"><div class="newscontent"><img src="${x.img}"><div><img src="${x.b.logo}" style="width:180px"><h1>${x.title}: ${x.name}</h1><p>${fs.map(v=>'✓ '+v).join('<br>')}</p><h2 style="font-size:48px;color:#e30613">${x.price}</h2><p><b>${x.cta}</b><br>${x.b.addr} • ${x.b.phone}</p></div></div></div>`}function text(x){return `🔥 ${x.title} w ${x.b.n}!

${x.name}
${x.features.map(v=>'✅ '+v).join('
')}

Cena: ${x.price}

📍 ${x.b.addr}
☎ ${x.b.phone}
🌐 ${x.b.web}

#${x.b.n.replace(/\s/g,'')} #RTV #AGD #Promocja`}function render(){let x=d();let c=$('canvas');c.className=cls(x);c.innerHTML=x.f==='reels'?reels(x):x.f==='news'?news(x):post(x);$('postText').value=text(x)}document.querySelectorAll('input,select,textarea').forEach(e=>e.addEventListener('input',render));document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{$('format').value=b.dataset.f;render()});$('gen').onclick=render;$('copy').onclick=()=>{navigator.clipboard&&navigator.clipboard.writeText($('postText').value);alert('Skopiowano tekst')};$('imgFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=v=>{uploaded=v.target.result;render()};r.readAsDataURL(f)};function dl(n,c,t='text/plain'){let blob=new Blob([c],{type:t}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=n;a.click()}$('down').onclick=()=>dl('ELKASS_social_podglad.html',`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="social-studio.css"><body style="margin:0;background:#eef2f7;display:grid;place-items:center;min-height:100vh">${$('canvas').outerHTML}</body>`,'text/html');$('pack').onclick=()=>dl('ELKASS_SOCIAL_STUDIO_EXPORT.json',JSON.stringify({data:d(),postText:$('postText').value,woodyboy:'Social Engine Core'},null,2),'application/json');render();